### ISSUE TITLE
Issue about hypergraph convolution

### ISSUE THREAD

**Issue by Bennie61** [Yue-Group/HGNN#18]
Hi, thank you very much for your contribution. I would like to ask you a question.
Assuming that I have built the hypergraph and have the original feature vectors for all nodes, I just want to refine the feature with the convolution operation and then save the refined features for my subsequent tasks. I just need the convolution operation, whereas I don't need to do the vertex classification task on the hypergraph structure. **In other words, can convolution operations be extracted separately from HGNN?**
How can I achieve it? still need network structure? Could you please give me some good suggestions? 
Many thanks for your help and looking forward to your valuable advice.

**Comment by yifanfeng97** [comment]
Hi!
    I'm glad that our work can help you. I have distilled the core code of HGNN convolution in the following. The following code assumes the hypergraph incidence matrix H has been computed. Welcome to use our toolbox for hypergraph learning: https://github.com/iMoonLab/DeepHypergraph.
Best
Yifan 

``` python
import torch
import torch.nn as nn
class HGNNConv(nn.Module):
    def __init__(self, dim_in, dim_out):
        super().__init__()
        self.Theta = nn.Sequential(
            nn.Linear(dim_in, dim_out),
            nn.BatchNorm1d(dim_out),
            nn.ReLU(),
            nn.Dropout()
        )

    def forward(self, X, G):
        X = self.Theta(X)
        X = torch.matmul(G, X)
        return X

class HGNN(nn.Module):
    def __init__(self, n_class, dim_in, dim_hid=32):
        super().__init__()
        self.conv1 = HGNNConv(dim_in, dim_hid)
        self.conv2 = HGNNConv(dim_hid, dim_hid)
        self.cls_layer = nn.Linear(dim_hid, n_class)
    
    def forward(self, X, G):
        X = self.conv1(X, G)
        g_ft = self.conv2(X, G)
        out = self.cls_layer(g_ft)
        return out

def incidence2G(H, symmetric=True):
    if symmetric:
        Dv = H.sum(dim=1, keepdim=True)
        De = H.sum(dim=0, keepdim=True)
        Dv_12 = Dv**(-1/2)
        Dv_12[torch.isinf(Dv_12)] = 0
        De_1 = De**(-1)
        De_1[torch.isinf(De_1)] = 0
        G = torch.matmul((Dv_12 * H), (De_1 * H * Dv_12).T)
    else:
        # norm row
        norm_r = 1/H.sum(dim=1, keepdim=True)
        norm_r[torch.isinf(norm_r)] = 0
        # norm col
        norm_c = 1/H.sum(dim=0, keepdim=True)
        norm_c[torch.isinf(norm_c)] = 0
        # gen G
        G = torch.matmul((norm_r * H), (norm_c * H).T)
    return G

G = incidence2G(H)
```

**Comment by yifanfeng97** [comment]
In DHG, we also provide this: https://deephypergraph.readthedocs.io/en/latest/start/high_order/hypergraph.html#smoothing-with-hgnn-s-laplacian

**Comment by Bennie61** [comment]
Many Thanks !!! Wish you all the best.
