### ISSUE TITLE
Get killed every time

### ISSUE THREAD

**Issue by JCwww** [Yue-Group/HGNN#4]
Hi, great work!
But I got this every time:

/root/HGNN/config/config.py:21: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  cfg = yaml.load(f)
Constructing hypergraph incidence matrix!
(It may take several minutes! Please wait patiently!)
Killed

No other error report, can you help me?

**Comment by yifanfeng97** [comment]
The process of constructing hypergraph incidence matrix may take much CPU memory. Make sure that your device has enough memory to run this code.
Best
